### ISSUE TITLE
Where are the versions numbers stored?

### ISSUE THREAD

**Issue by aboyd003** [nf-core/cageseq#19]
The link in the text below redirects to an empty page?

"First, go to the nf-core/cageseq releases page and find the latest version number - numeric only (eg. 1.3.1). Then specify this when running the pipeline with -r (one hyphen) - eg. -r 1.3.1."

**Comment by mashehu** [comment]
cageseq hasn't been released yet, so it doesn't have a version number. Use `-r dev` instead.
