### ISSUE TITLE
cageseq error

### ISSUE THREAD

**Issue by gk1610** [nf-core/cageseq#71]
Hi 

I am getting input tuple error. Could you please help me with this?

```
WARN: Access to undefined parameter `config_profile_contact` -- Initialise it to a default value eg. `params.config_profile_contact = some_value`
WARN: Access to undefined parameter `config_profile_url` -- Initialise it to a default value eg. `params.config_profile_url = some_value`
Run Name          : big_payne
Input             : sample_1/*R1.fastq.gz
5' artifacts      : software/cageseq/assests/artifacts_5end.fasta
3' artifacts      : software/cageseq/assests/artifacts_3end.fasta
trim_ecop         : true
trim_linker       : true
trim_5g           : true
trim_artifacts    : true
eco_site          : CAGCAG
linker_seq        : TCGTATGCCGTCTTC
Remove rRNA       : true
Aligner           : STAR
STAR Index        : hg38.analysisSet.chroms
Min. cluster      : 30
Cluster Threshold : 0.2
bigwig output     : Yes
Save Reference    : false
Max Resources     : 160 GB memory, 20 cpus, 5d 23h time per job
Output dir        : test_results/
Launch dir        : software
Working dir       : software/work
Script dir        : software/cageseq
User              : KG
Config Profile    : chimera
Config Files      : software/cageseq/nextflow.config
----------------------------------------------------
No signature of method: java.lang.Boolean.getFileSystem() is applicable for argument types: () values: []


WARN: Input tuple does not match input set cardinality declared by process `fastqc` -- offending value: sample_1/sample.R1.fastq.gz
WARN: Input tuple does not match input set cardinality declared by process `trim_adapters` -- offending value: sample_1/sample.R1.fastq.gz
[-        ] process > get_software_versions -
[-        ] process > convert_gtf           -
-[nf-core/cageseq] Pipeline completed with errors-

```

**Comment by mashehu** [comment]
Hi,
Can you run `ls sample_1/*R1.fastq.gz` and post the resutl here, to check how the input is formatted.

**Comment by gk1610** [comment]
```
so this file exists but it is a soft link from a different folder

when I run this; it works it shows up as a link. Can that be a problem?
ls sample_1/*R1.fastq.gz
sample_1/L004_001.R1.fastq.gz
```

**Comment by mashehu** [comment]
hmm, worth to give it a try with a non-symlinked file

**Comment by gk1610** [comment]
I just did and same error. Could you please give more suggestions or ideas to debug?

No signature of method: java.lang.Boolean.getFileSystem() is applicable for argument types: () values: []

```

WARN: Input tuple does not match input set cardinality declared by process `fastqc` -- offending value: sample_1/*R1.fastq.gz
WARN: Input tuple does not match input set cardinality declared by process `trim_adapters` -- offending value: sample_1/*R1.fastq.gz
[-        ] process > get_software_versions -
[-        ] process > convert_gtf           -
[-        ] process > get_chrom_sizes       -
[-        ] process > fastqc                -
[-        ] process > trim_adapters         -
-[nf-core/cageseq] Pipeline completed with errors-

```

**Comment by mashehu** [comment]
what is the java and nextflow version you are using?

**Comment by gk1610** [comment]
I have create my own  configure profile; here is the copy of it.

`params {
    // Genomes reference file paths
    genomes {
        'GRCh38.Gencode.v30' {
            fasta = "/GRCh38/FASTA/GRCh38.primary_assembly.genome.fa"
            gtf =   "/GRCh38/Gencode/release_30/gencode.v30.primary_assembly.annotation.gtf"
            star     = "/GRCh38/star/2.7.1a/Gencode.v30.overhang100/chr_primary"
            reflat   = "/GRCh38/Gencode/release_30/gencode.v30.primary_assembly.annotation.reflat"
            rrna     = "/GRCh38/Gencode/release_30/gencode.v30.rRNA.interval.list"
            rsem     = "GRCh38/rsem/1.3.0/gencode.v30.bam/GRCh38.primary_assembly"
            globin   = "/GRCh38/Gencode/release_30/globin_gene.gtf"
        }
    }
    version {
        cutadapt = '4.1'
        samtools = '1.17'
        star = '2.7.5b'
        R = '3.5.3'
        fastqc = 'v0.11.9'
        paraclu = '021-02-04'
        sortmerna = '4.3.6'
        py_packages = '3.7'
        python = '3.7.3'
        bedtools='v2.29.2'
        read_distribution.py = '5.0.1'
        bowtie = '1.3.0'
        multiqc = '1.10.1'
    }
}


process {
    // default executor values
    cpus = 1
    memory = 2.GB
    time = 1.h

    // Environmental settings and computational resources
    withName:convert_gtf {
        module = 'pigz'
        cpus = 1
        memory = 1.GB // 1x6
        time = {2.h * task.attempt}
    }
    withName:get_chrom_sizes {
        module = 'pigz'
        cpus = 1
        memory = {1.GB * task.attempt} // 1x6
        time = {3.h * task.attempt}
    }
    withName:fastqc {
        module = {"fastqc/${params.version.fastqc}"}
        cpus = 4
        memory = 2.GB  // 2*4
        time = {4.h * task.attempt}
    }
    withName:make_STAR_index {
        module = {"star/${params.version.star}"}
        cpus = 1
        memory = 5.GB  // 12*5
        time = {4.h * task.attempt}
    }
    withName:trim_adapters {
        module = {"cutadapt/${params.version.cutadapt}"}
        cpus = 4
        memory = 2.GB  // 2*4
        time = {4.h * task.attempt}
    }
    withName:trim_5g {
        module = {"cutadapt/${params.version.cutadapt}"}
        cpus = 4
        memory = 2.GB  // 2*4
        time = {4.h * task.attempt}
    }
    withName:trim_artifacts {
        module = {"cutadapt/${params.version.cutadapt}"}
        cpus = 4
        memory = 2.GB  // 2*4
        time = {4.h * task.attempt}
    }
    withName:sortmerna {
        module = {"sortmerna/${params.version.sortmerna}"}
        cpus = 5
        memory = 2.GB // 4*2
        time = {10.h * task.attempt}
    }
    withName:trimmed_fastqc {
        module = {"samtools/${params.version.samtools}"}
        cpus = 1
        memory = 2.GB // 1*2
        time = {4.h * task.attempt}
    }
    withName:star {
        module = {"star/${params.version.star}"}
        cpus = 12
        memory = 5.GB  // 12*5
        time = {10.h * task.attempt}
    }
    withName:samtools_stats {
        module = {"samtools/${params.version.samtools}"}
        cpus = 1
        memory = 2.GB // 1*2
        time = {4.h * task.attempt}
    }
    withName:get_ctss {
        module = {"subread/${params.version.subread}"}
        cpus = 12
        memory = 2.GB // 12*2
        time = {2.h * task.attempt}
    }
    withName:make_bigwig {
        module = {"bedtools/${params.version.bedtools}:python/3.7.3:py_packages/3.7"}
        cpus = 2
        memory = 6.GB // 2*6
        time = {12.h * task.attempt}
    }
    withName:cluster_ctss {
        module = {"bedtools/${params.version.bedtools}:paraclu/${params.version.paraclu}:python/3.7.3:py_packages/3.7"}
        cpus = 1
        memory = 24.GB
        time = {6.h * task.attempt}
    }
    withName:generate_counts {
        module = {"bedtools/${params.version.bedtools}:python/3.7.3:py_packages/3.7"}
        cpus = 3
        memory = 20.GB
        time = {6.h * task.attempt}
    }
    withName:ctss_qc {
        module = {"bedtools/${params.version.bedtools}:python/3.7.3:py_packages/3.7"}
        cpus = 2
        memory = 16.GB // 2*16
        time = {8.h * task.attempt}
    }
    withName:multiqc {
        module = {"python/3.7.3:py_packages/3.7:gcc/7.3.0"}
        cpus = 2
        memory = 16.GB // 2*16
        time = {2.h * task.attempt}
    }
    withName:output_documentation {
        module = 'pigz'
        cpus = 1
        memory = 1.GB // 1x6
        time = {12.h * task.attempt}
    }

}

`

**Comment by gk1610** [comment]
nextflow/22.10.6
java/11.0.2/

**Comment by mashehu** [comment]
Do the tests run, i.e. can you run it with `-profile test` ?

**Comment by mashehu** [comment]
might also be a nextflow dsl1/dsl2 problem. This pipeline is unfortunately still DSL1 (and nextlfow dropped it's support anymore since 22.10.x). I hope I can get out a new version at the end of this summer, but for now could you maybe downgrade your nextflow version?

**Comment by gk1610** [comment]
I am now trying
nextflow/19.10.0
java/1.8.0_211/

`nextflow run cageseq -profile 'test'

I changed projectDir to a specified path everywhere because this nextflow has no space for projectdir argument.
But it gives me this error

`Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: 
cageseq/nextflow.config

**Comment by mashehu** [comment]
can you please post the modified cageseq/nextflow.config here?

**Comment by mashehu** [comment]
closing because of lack of response
